In [ ]:
#Crop yield for 4 farms over 5 seasons(in tons)
import numpy as np
crop_yield=np.array([
    [12.5,13.2,14.1,13.8,15.2], #Farm1 -North Region
    [10.3,11.5,10.8,12.1,11.9],# Farm2 - South Region
    [15.1,14.8,16.2,15.5,16.8],# Farm 3-East Region
    [11.2,10.9,12.3,11.7,12.8] #Farm 4- West Region
])
print("Crop yields array (tons):",crop_yield)
print(f'\nShape:{crop_yield.shape}')
print(f'\nData type:{crop_yield.dtype}')
print(f'\nTotal elements:{crop_yield.size}')
print(f'\nNumber of dimensions:{crop_yield.ndim}')

Crop yields array (tons): [[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

Shape:(4, 5)

Data type:float64

Total elements:20

Number of dimensions:2


In [ ]:
#Agricultural analysis operations
import numpy as np
total_yield=np.sum(crop_yield)
avg_yield_per_farm=np.mean(crop_yield,axis=1)  #axis= 1 represents row-wise
avg_yield_per_season=np.mean(crop_yield,axis=0) #axis=0 represents column-wise
max_yield=np.max(crop_yield)
min_yield=np.min(crop_yield)
max_yield1=np.max(crop_yield,axis=1) # farm which has the max yield
min_yield1=np.min(crop_yield,axis=0) # season-wise max yield

print(f'\nTotal Production: {total_yield}tons')
print(f'Average per farm:{avg_yield_per_farm}tons')
print(f'Average per season:{avg_yield_per_season}tons')
print(f'Maximum yield:{max_yield}tons')
print(f'Minimum yield:{min_yield}tons')
print(max_yield1)
print(min_yield1)


Total Production: 262.7tons
Average per farm:[13.76 11.32 15.68 11.78]tons
Average per season:[12.275 12.6   13.35  13.275 14.175]tons
Maximum yield:16.8tons
Minimum yield:10.3tons
[15.2 12.1 16.8 12.8]
[10.3 10.9 10.8 11.7 11.9]


In [ ]:
#Find best performing farm
best_farm= np.argmax(avg_yield_per_farm)
#np.argmax() does not return the max value itself- it returns where that value is located

print("\nBest performing farm: Farm",best_farm+1) #index is less than the original length, so we are adding 1
print("Average yield:",round(avg_yield_per_farm[best_farm],2),"tons")
print(best_farm) #returns the index of the best farm


Best performing farm: Farm 3
Average yield: 15.68 tons
2


In [ ]:
#Boolean indexing: find exceptional yields
exception= crop_yield>16
print("Exceptional crop yields:",crop_yield[exception])
print("")
print(exception)

Exceptional crop yields: [16.2 16.8]

[[False False False False False]
 [False False False False False]
 [False False  True False  True]
 [False False False False False]]


In [ ]:
#Conditional operations:classify yields
categories=np.where(crop_yield>16,'High',
                    np.where(crop_yield>14,'Medium','Low'))
print(categories)

[['Low' 'Low' 'Medium' 'Low' 'Medium']
 ['Low' 'Low' 'Low' 'Low' 'Low']
 ['Medium' 'Medium' 'High' 'Medium' 'High']
 ['Low' 'Low' 'Low' 'Low' 'Low']]
